export App from './App'
export Home from './Home'
export DevilFruit from './DevilFruit'
export Characters from './Characters'
export Anime from './Anime'
export Manga from './Manga'
export Games from './Games'
